AllCops:
  TargetRubyVersion: 2.4

inherit_from: 
  - https://raw.githubusercontent.com/everypolitician/everypolitician-data/master/.rubocop_base.yml
  - .rubocop_todo.yml

# Allow long Pull Request numbers as integers
Style/NumericLiterals:
  MinDigits: 6
